# Generated by Django 4.2.11 on 2026-04-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('temp_agua_min', models.FloatField(help_text='Temperatura mínima del agua (°C)')),
                ('temp_agua_max', models.FloatField(help_text='Temperatura máxima del agua (°C)')),
                ('viento_max', models.FloatField(help_text='Velocidad de viento máxima tolerable (km/h)')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('mar', 'Mar'), ('rio', 'Río'), ('embalse', 'Embalse'), ('lago', 'Lago')], default='mar', max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('longitud_cm', models.FloatField(blank=True, null=True)),
                ('temperatura_agua', models.FloatField(blank=True, null=True)),
                ('velocidad_viento', models.FloatField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='capturas/')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='api.especie')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='api.spot')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
