# Generated by Django 4.2.11 on 2026-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='es_personalizado',
            field=models.BooleanField(default=False, help_text='True si fue creado desde el mapa libre'),
        ),
    ]
