# Generated by Django 4.2.11 on 2026-06-22 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='creador',
            field=models.ForeignKey(blank=True, help_text='Si es None, el spot es global. Si tiene creador, la visibilidad depende de su perfil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spots_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
