# Generated by Django 4.2.11 on 2026-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_spot_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_publico',
            field=models.BooleanField(default=True),
        ),
    ]
